### ISSUE TITLE
Bug !

### ISSUE THREAD

**Issue by mikhoul** [raspopov/SageLinks#1]
I tried to install/use it but it "crash"... 

![http://i.imgur.com/qdhWL6p.png](http://i.imgur.com/qdhWL6p.png)

I use Win 7 64bit and I have even tried to put the DLL in the same folder as the executable but it crash too ...  :disappointed:

![http://i.imgur.com/JCM3beN.png](http://i.imgur.com/JCM3beN.png)

 What I can do ? 

Regards.  :sunglasses:

**Comment by raspopov** [comment]
If vc_redist.*.exe was installed correctly your issue can not happen. Please re-install Microsoft redistributable packages, DLL won't work if it copied manually.

**Comment by mikhoul** [comment]
DDL was not copied manually and for sure I tried twice to reinstall after I moved the DLL directly in the same folder.

![http://i.imgur.com/xh58fMB.png](http://i.imgur.com/xh58fMB.png)

**Comment by raspopov** [comment]
Where is corresponding 32-bit DLL?

**Comment by mikhoul** [comment]
Ohhhhhh !    I was thinking since my OS is 64bit I had (only) to install the 64bit of the runtime... but since your .exe is 32bit (it is ?) it make sense that I have the 32 bit to install too.

-=-=-=-=-=-

Just installed the x86 Runtime and everything work fine... :grinning:    

I was thinking that installing the X64 version would have installed the X86 runtime too cause I don't remember installing X86 version AND X64 of various MSFT runtime. :astonished:

Thanks a lot for the help !
