### ISSUE TITLE
List files and folders that are the target of links

### ISSUE THREAD

**Issue by beppe9000** [raspopov/SageLinks#11]
I would like to check folders before archiving them to an external drive to make sure I am not creating orphaned links in the process.

I would give the program a path and the output would be the list of links that use any of the files in the provided path as their target.

Is it possible/feasible ?

**Comment by raspopov** [comment]
I can suggest to use an archiver with a knowledge about links like [WinRaR](https://www.rarlab.com/), you can pack links as links or as its targets.

**Comment by beppe9000** [comment]
> 
> 
> I can suggest to use an archiver with a knowledge about links like [WinRaR](https://www.rarlab.com/), you can pack links as links or as its targets.

My use case is the opposite of that: I have a folder, some links (somewhere else) might point to it (or files inside). When I remove the folder the links would become orphaned. I would like to scan the folder and list the links so I can deal with them (before failures happen).

**Comment by raspopov** [comment]
Scan all, sort by target.

**Comment by beppe9000** [comment]
Makes sense, thanks!
