### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by mikhoul** [raspopov/SageLinks#2]
Hi,

Would it be possible to ad Hard-Links ? 
![http://i.imgur.com/nPNxEbp.png](http://i.imgur.com/nPNxEbp.png)

**Comment by raspopov** [comment]
Why? IMHO hardlink can not be broken...

**Comment by mikhoul** [comment]
On the left side of the screenshot there is a hardlink  but when I scan with Sagelinks he did not find hardlinks at all. 

I use Link shell extension it add an different overlay to symlink, hardlink & junction but I'd like to be able to find it more quickly with Sagelinks.

**Comment by raspopov** [comment]
Why you need hardlinks?

**Comment by mikhoul** [comment]
Cause it's more EZ to find which are the "real" files and take space on the disk and which one are "hard link". Also it's more EZ to visualize the structure of the disk when I know where are the different links to know what is virtual and what is real (files &folders).  :blush:

A good example is in the WinSxS folder

**Comment by raspopov** [comment]
Hard link is a **real** file/folder. So hard link cannot be broken and no point in SageLinks usage.

**Comment by mikhoul** [comment]
A Hard<ins>**link**</ins> (like the name suggest) is a link like junctions, and symbolic links and <ins>**NOT**</ins> a real file.  Also Folders CAN'T be hard-linked only files on the same volume.

There is ONLY 3 .bin files in this folder AND a Hardlink that take ZERO space on disk (even if the system see the size of the original file it is only a pointer to the file embedded in the NTFS file system)
![http://i.imgur.com/wjrjdr9.png](http://i.imgur.com/wjrjdr9.png)

More information here to have a better understanding of Hardlinks: 
- https://msdn.microsoft.com/en-us/library/windows/desktop/aa365006%28v=vs.85%29.aspx
- http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html#hardlinks
- www.2brightsparks.com/resources/articles/NTFS-Hard-Links-Junctions-and-Symbolic-Links.pdf

Regards :computer:

**Comment by raspopov** [comment]
Please read your own information URLs to understand what is a hardlink. Also in the first URL you can learn why hardlink is not counted in the total folder size.
