### ISSUE TITLE
Reporting some links as broken even when they seem to be valid

### ISSUE THREAD

**Issue by Ketrel** [raspopov/SageLinks#4]
When I run this, I'm getting a number of symlinks identified as broken, but they appear to be fully valid and functional.

The symlink exists.
The target exists.
Opening the symlink opens the target.

However, it's still showing up as broken.

**Comment by raspopov** [comment]
Screenshot please

**Comment by Ketrel** [comment]
Sage Showing Broken Symlink: http://i.imgur.com/A7HO6UN.png
Symlink file location: http://i.imgur.com/Op9DPmt.png  
Target file location: http://i.imgur.com/ONIinII.png  
Target opened in Notepad++: http://i.imgur.com/HBiKODT.png 
Symlink opened in Notepad++: http://i.imgur.com/YLKwYgH.png

**Comment by raspopov** [comment]
Thank you! Seems something wrong with a file access permissions, looks like SageLinks is failed to read symlink and Explorer also shows a wrong zero byte size. Try to run SageLinks with administrative rights.

**Comment by Ketrel** [comment]
I originally tried it as administrator suspecting the same thing. 
It didn't make a difference.  The same files were getting flagged.

Also, I moved those files to the same physical drive and am using hardlinks currently, so I can't do further testing with those specifically.

If you have any test scenarios you'd like me to try, I can create the symlinks manually.

**Comment by raspopov** [comment]
Try a new (more error reports) version of SageLinks please.
