### ISSUE TITLE
Incompatibility with volumes using Windows Data De-Duplication.

### ISSUE THREAD

**Issue by cuttersw** [raspopov/SageLinks#5]
Reports de-duplicated files (files containing reparse points) as broken, and does not show type or target.
![image](https://cloud.githubusercontent.com/assets/25127863/21959922/9aa546c6-daa4-11e6-9169-532083d6ffc7.png)

**Comment by raspopov** [comment]
Thank you. SageLinks not yet supported the de-duplicated files (tagged as IO_REPARSE_TAG_DEDUP).

**Comment by raspopov** [comment]
Temporary masked in a new version of SageLinks.
