### ISSUE TITLE
Getting 0xEA on every link

### ISSUE THREAD

**Issue by 1024mb** [raspopov/SageLinks#8]
When I scan a directory I get this message with almost every symlink (be it broken or not):

`There is more data available: 0xEA`

I'm using windows 10. Both times I've tried SageLinks, one before and one after reinstalling Windows it gave the same results.

**Comment by raspopov** [comment]
Very long paths (> 260 symbols) probably.

**Comment by 1024mb** [comment]
Hey, thanks for the commit but I don't think that is the problem. For example on one entry the full path for the symlink and for the original file are 122 characters long, both of them. There is another file that is 135 chars long also. Will try the new release when you publish it but Idk if that is the issue.

**Comment by raspopov** [comment]
Ok, try it: https://github.com/raspopov/SageLinks/releases

**Comment by 1024mb** [comment]
> 
> 
> Ok, try it: [raspopov/SageLinks/releases](https://github.com/raspopov/SageLinks/releases)

Thanks, that was the problem. It now works well.
